[package]
name = "fring"
version = "0.2.1"
edition = "2021"
authors = ["David Lawrence <dlaw@dlaw.me>"]
license = "MIT"
repository = "https://github.com/dlaw/fring/"
description = "Lightweight, no_std, and *fast* ring buffer"
categories = ["embedded", "no-std"]
keywords = ["ringbuffer"]
